### ISSUE TITLE
[Question] Can I use windows?

### ISSUE THREAD

**Issue by ThakurAnunaya** [google-research/android_world#196]
Hi 

Unfortunately, I do not have ubuntu system. I want to try this on windows. Can I use windows?

**Comment by NingLi670** [comment]
Hi! I have change the codes to make AndroidWorld runnable on Windows operating system. If you are interested in it, please refer to https://github.com/google-research/android_world/pull/227

**Comment by crawles** [comment]
This is awesome, thank you! I will take a closer look tomorrow

Chris

**Comment by Jinxhy** [comment]
> > Hi! I have change the codes to make AndroidWorld runnable on Windows operating system. If you are interested in it, please refer to [#227](https://github.com/google-research/android_world/pull/227)
> 
> This works for me! Thanks for your code!

Hi @mengzchen , I have tried the latest version of AndroidWorld on Windows 11 and it keeps throwing errors as below:
```
(android_world) D:\code\mobile_agent_privacy\android_world-main\android_world-main>python minimal_task_runner.py --task=ContactsAddContact
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1746788129.468793   19436 trace.cc:89] Unknown tracer: none
E0509 20:55:31.698804 19436 adb_controller.py:131] Failed to execute ADB command (try 1 of 3): [adb -P 5037 -s emulator-5554 install -r -t -g C:\Users\jinxw\AppData\Local\Temp\tmp89p08pwe.apk]
Traceback (most recent call last):
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 122, in execute_command
    cmd_output = subprocess.check_output(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.
E0509 20:55:31.718319 19436 adb_controller.py:135] **stdout**:
E0509 20:55:31.718319 19436 adb_controller.py:137]     b'adb: failed to open C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk: No such file or directory'
E0509 20:55:31.718319 19436 adb_controller.py:137]     b'Performing Streamed Install'
E0509 20:55:36.217509 19436 adb_controller.py:131] Failed to execute ADB command (try 2 of 3): [adb -P 5037 -s emulator-5554 install -r -t -g C:\Users\jinxw\AppData\Local\Temp\tmp89p08pwe.apk]
Traceback (most recent call last):
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 122, in execute_command
    cmd_output = subprocess.check_output(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.
E0509 20:55:36.219012 19436 adb_controller.py:135] **stdout**:
E0509 20:55:36.219012 19436 adb_controller.py:137]     b'adb: failed to open C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk: No such file or directory'
E0509 20:55:36.219012 19436 adb_controller.py:137]     b'Performing Streamed Install'
Traceback (most recent call last):
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 122, in execute_command
    cmd_output = subprocess.check_output(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\minimal_task_runner.py", line 130, in <module>
    app.run(main)
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\minimal_task_runner.py", line 126, in main
    _main()
  File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\minimal_task_runner.py", line 88, in _main
    env = env_launcher.load_and_setup_env(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\env_launcher.py", line 120, in load_and_setup_env
    env = _get_env(console_port, adb_path, grpc_port)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\env_launcher.py", line 35, in _get_env
    controller = android_world_controller.get_controller(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\android_world_controller.py", line 324, in get_controller
    return AndroidWorldController(android_env_instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\android_world_controller.py", line 167, in __init__
    self._env = apply_a11y_forwarder_app_wrapper(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\android_world_controller.py", line 140, in apply_a11y_forwarder_app_wrapper
    return a11y_grpc_wrapper.A11yGrpcWrapper(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\wrappers\a11y_grpc_wrapper.py", line 121, in __init__
    self._install_a11y_forwarding_apk()
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\wrappers\a11y_grpc_wrapper.py", line 197, in _install_a11y_forwarding_apk
    install_response = self._env.execute_adb_call(install_request)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\environment.py", line 150, in execute_adb_call
    return self._coordinator.execute_adb_call(call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\coordinator.py", line 180, in execute_adb_call
    return self._adb_call_parser.parse(call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_call_parser.py", line 111, in parse
    return self._handlers[command_type](request, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_call_parser.py", line 295, in _install_apk
    response, _ = self._execute_command(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_call_parser.py", line 81, in _execute_command
    command_output = self._adb_controller.execute_command(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 147, in execute_command
    raise errors.AdbControllerError(
android_env.components.errors.AdbControllerError: Error executing adb command: [adb -P 5037 -s emulator-5554 install -r -t -g C:\Users\jinxw\AppData\Local\Temp\tmp89p08pwe.apk]
Caused by: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.
adb stdout: [b'adb: failed to open C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk: No such file or directory\r\nPerforming Streamed Install\r\n']
adb stderr: [None]
```

Could you please advise any further changes needed to be made to the code?

Best regards,
Jinx

**Comment by ZeruiQin** [comment]
> > > Hi! I have change the codes to make AndroidWorld runnable on Windows operating system. If you are interested in it, please refer to [#227](https://github.com/google-research/android_world/pull/227)
> > 
> > 
> > This works for me! Thanks for your code!
> 
> Hi [@mengzchen](https://github.com/mengzchen) , I have tried the latest version of AndroidWorld on Windows 11 and it keeps throwing errors as below:
> 
> ```
> (android_world) D:\code\mobile_agent_privacy\android_world-main\android_world-main>python minimal_task_runner.py --task=ContactsAddContact
> WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
> E0000 00:00:1746788129.468793   19436 trace.cc:89] Unknown tracer: none
> E0509 20:55:31.698804 19436 adb_controller.py:131] Failed to execute ADB command (try 1 of 3): [adb -P 5037 -s emulator-5554 install -r -t -g C:\Users\jinxw\AppData\Local\Temp\tmp89p08pwe.apk]
> Traceback (most recent call last):
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 122, in execute_command
>     cmd_output = subprocess.check_output(
>                  ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 466, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.
> E0509 20:55:31.718319 19436 adb_controller.py:135] **stdout**:
> E0509 20:55:31.718319 19436 adb_controller.py:137]     b'adb: failed to open C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk: No such file or directory'
> E0509 20:55:31.718319 19436 adb_controller.py:137]     b'Performing Streamed Install'
> E0509 20:55:36.217509 19436 adb_controller.py:131] Failed to execute ADB command (try 2 of 3): [adb -P 5037 -s emulator-5554 install -r -t -g C:\Users\jinxw\AppData\Local\Temp\tmp89p08pwe.apk]
> Traceback (most recent call last):
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 122, in execute_command
>     cmd_output = subprocess.check_output(
>                  ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 466, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.
> E0509 20:55:36.219012 19436 adb_controller.py:135] **stdout**:
> E0509 20:55:36.219012 19436 adb_controller.py:137]     b'adb: failed to open C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk: No such file or directory'
> E0509 20:55:36.219012 19436 adb_controller.py:137]     b'Performing Streamed Install'
> Traceback (most recent call last):
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 122, in execute_command
>     cmd_output = subprocess.check_output(
>                  ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 466, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\minimal_task_runner.py", line 130, in <module>
>     app.run(main)
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\absl\app.py", line 308, in run
>     _run_main(main, args)
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\absl\app.py", line 254, in _run_main
>     sys.exit(main(argv))
>              ^^^^^^^^^^
>   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\minimal_task_runner.py", line 126, in main
>     _main()
>   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\minimal_task_runner.py", line 88, in _main
>     env = env_launcher.load_and_setup_env(
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\env_launcher.py", line 120, in load_and_setup_env
>     env = _get_env(console_port, adb_path, grpc_port)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\env_launcher.py", line 35, in _get_env
>     controller = android_world_controller.get_controller(
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\android_world_controller.py", line 324, in get_controller
>     return AndroidWorldController(android_env_instance)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\android_world_controller.py", line 167, in __init__
>     self._env = apply_a11y_forwarder_app_wrapper(
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\android_world_controller.py", line 140, in apply_a11y_forwarder_app_wrapper
>     return a11y_grpc_wrapper.A11yGrpcWrapper(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\wrappers\a11y_grpc_wrapper.py", line 121, in __init__
>     self._install_a11y_forwarding_apk()
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\wrappers\a11y_grpc_wrapper.py", line 197, in _install_a11y_forwarding_apk
>     install_response = self._env.execute_adb_call(install_request)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\environment.py", line 150, in execute_adb_call
>     return self._coordinator.execute_adb_call(call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\coordinator.py", line 180, in execute_adb_call
>     return self._adb_call_parser.parse(call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_call_parser.py", line 111, in parse
>     return self._handlers[command_type](request, timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_call_parser.py", line 295, in _install_apk
>     response, _ = self._execute_command(
>                   ^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_call_parser.py", line 81, in _execute_command
>     command_output = self._adb_controller.execute_command(
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 147, in execute_command
>     raise errors.AdbControllerError(
> android_env.components.errors.AdbControllerError: Error executing adb command: [adb -P 5037 -s emulator-5554 install -r -t -g C:\Users\jinxw\AppData\Local\Temp\tmp89p08pwe.apk]
> Caused by: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.
> adb stdout: [b'adb: failed to open C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk: No such file or directory\r\nPerforming Streamed Install\r\n']
> adb stderr: [None]
> ```
> 
> Could you please advise any further changes needed to be made to the code?
> 
> Best regards, Jinx

Have you solved this problem? I got the same one

**Comment by jturner65** [comment]
> > > > Hi! I have change the codes to make AndroidWorld runnable on Windows operating system. If you are interested in it, please refer to [#227](https://github.com/google-research/android_world/pull/227)
> > > 
> > > 
> > > This works for me! Thanks for your code!
> > 
> > 
> > Hi [@mengzchen](https://github.com/mengzchen) , I have tried the latest version of AndroidWorld on Windows 11 and it keeps throwing errors as below:
> > ```
> > (android_world) D:\code\mobile_agent_privacy\android_world-main\android_world-main>python minimal_task_runner.py --task=ContactsAddContact
> > WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
> > E0000 00:00:1746788129.468793   19436 trace.cc:89] Unknown tracer: none
> > E0509 20:55:31.698804 19436 adb_controller.py:131] Failed to execute ADB command (try 1 of 3): [adb -P 5037 -s emulator-5554 install -r -t -g C:\Users\jinxw\AppData\Local\Temp\tmp89p08pwe.apk]
> > Traceback (most recent call last):
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 122, in execute_command
> >     cmd_output = subprocess.check_output(
> >                  ^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 466, in check_output
> >     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 571, in run
> >     raise CalledProcessError(retcode, process.args,
> > subprocess.CalledProcessError: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.
> > E0509 20:55:31.718319 19436 adb_controller.py:135] **stdout**:
> > E0509 20:55:31.718319 19436 adb_controller.py:137]     b'adb: failed to open C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk: No such file or directory'
> > E0509 20:55:31.718319 19436 adb_controller.py:137]     b'Performing Streamed Install'
> > E0509 20:55:36.217509 19436 adb_controller.py:131] Failed to execute ADB command (try 2 of 3): [adb -P 5037 -s emulator-5554 install -r -t -g C:\Users\jinxw\AppData\Local\Temp\tmp89p08pwe.apk]
> > Traceback (most recent call last):
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 122, in execute_command
> >     cmd_output = subprocess.check_output(
> >                  ^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 466, in check_output
> >     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 571, in run
> >     raise CalledProcessError(retcode, process.args,
> > subprocess.CalledProcessError: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.
> > E0509 20:55:36.219012 19436 adb_controller.py:135] **stdout**:
> > E0509 20:55:36.219012 19436 adb_controller.py:137]     b'adb: failed to open C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk: No such file or directory'
> > E0509 20:55:36.219012 19436 adb_controller.py:137]     b'Performing Streamed Install'
> > Traceback (most recent call last):
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 122, in execute_command
> >     cmd_output = subprocess.check_output(
> >                  ^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 466, in check_output
> >     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\subprocess.py", line 571, in run
> >     raise CalledProcessError(retcode, process.args,
> > subprocess.CalledProcessError: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.
> > 
> > The above exception was the direct cause of the following exception:
> > 
> > Traceback (most recent call last):
> >   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\minimal_task_runner.py", line 130, in <module>
> >     app.run(main)
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\absl\app.py", line 308, in run
> >     _run_main(main, args)
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\absl\app.py", line 254, in _run_main
> >     sys.exit(main(argv))
> >              ^^^^^^^^^^
> >   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\minimal_task_runner.py", line 126, in main
> >     _main()
> >   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\minimal_task_runner.py", line 88, in _main
> >     env = env_launcher.load_and_setup_env(
> >           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\env_launcher.py", line 120, in load_and_setup_env
> >     env = _get_env(console_port, adb_path, grpc_port)
> >           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\env_launcher.py", line 35, in _get_env
> >     controller = android_world_controller.get_controller(
> >                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\android_world_controller.py", line 324, in get_controller
> >     return AndroidWorldController(android_env_instance)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\android_world_controller.py", line 167, in __init__
> >     self._env = apply_a11y_forwarder_app_wrapper(
> >                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\code\mobile_agent_privacy\android_world-main\android_world-main\android_world\env\android_world_controller.py", line 140, in apply_a11y_forwarder_app_wrapper
> >     return a11y_grpc_wrapper.A11yGrpcWrapper(
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\wrappers\a11y_grpc_wrapper.py", line 121, in __init__
> >     self._install_a11y_forwarding_apk()
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\wrappers\a11y_grpc_wrapper.py", line 197, in _install_a11y_forwarding_apk
> >     install_response = self._env.execute_adb_call(install_request)
> >                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\environment.py", line 150, in execute_adb_call
> >     return self._coordinator.execute_adb_call(call)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\coordinator.py", line 180, in execute_adb_call
> >     return self._adb_call_parser.parse(call)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_call_parser.py", line 111, in parse
> >     return self._handlers[command_type](request, timeout)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_call_parser.py", line 295, in _install_apk
> >     response, _ = self._execute_command(
> >                   ^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_call_parser.py", line 81, in _execute_command
> >     command_output = self._adb_controller.execute_command(
> >                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\software\anaconda3\envs\android_world\Lib\site-packages\android_env\components\adb_controller.py", line 147, in execute_command
> >     raise errors.AdbControllerError(
> > android_env.components.errors.AdbControllerError: Error executing adb command: [adb -P 5037 -s emulator-5554 install -r -t -g C:\Users\jinxw\AppData\Local\Temp\tmp89p08pwe.apk]
> > Caused by: Command '['D:/software/Android/Sdk/platform-tools/adb.exe', '-P', '5037', '-s', 'emulator-5554', 'install', '-r', '-t', '-g', 'C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk']' returned non-zero exit status 1.
> > adb stdout: [b'adb: failed to open C:\\Users\\jinxw\\AppData\\Local\\Temp\\tmp89p08pwe.apk: No such file or directory\r\nPerforming Streamed Install\r\n']
> > adb stderr: [None]
> > ```
> > 

> > Could you please advise any further changes needed to be made to the code?
> > Best regards, Jinx
> 
> Have you solved this problem? I got the same one

This fix https://github.com/google-research/android_world/issues/283#issuecomment-3248457629 fixed the "No such file or directory" bug I was having:

> this is a bug of android_env，change：D:\ProgramData\anaconda3\envs\android_world_py311\Lib\site-packages\android_env\components\adb_call_parser.py" :
> with tempfile.NamedTemporaryFile(**kwargs) as f: to with tempfile.NamedTemporaryFile(**kwargs, delete=False) as f:
