### ISSUE TITLE
Error when running tasks 

### ISSUE THREAD

**Issue by ThakurAnunaya** [google-research/android_world#198]
Hi 

I get the below error if I try to run any tasks: 
I am running the tasks on a automotive emulator. 

(android_world) thakur@INBAWN180334:/mnt/c/Users/anuthakur/Documents/android_world/android_world$ python minimal_task_runner.py --task=TurnOffWifiAndTurnOnBluetooth
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1733647234.404567   39939 trace.cc:89] Unknown tracer: none
W1208 08:40:59.817440 140126432224768 android_world_controller.py:98] Could not get a11y tree, retrying.
W1208 08:41:00.818300 140126432224768 android_world_controller.py:98] Could not get a11y tree, retrying.
W1208 08:41:01.819154 140126432224768 android_world_controller.py:98] Could not get a11y tree, retrying.
E1208 08:41:04.567514 140126432224768 adb_controller.py:131] Failed to execute ADB command (try 1 of 3): [adb -P 5037 -s emulator-5554 shell date 1015153423.00]
Traceback (most recent call last):
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/components/adb_controller.py", line 122, in execute_command
    cmd_output = subprocess.check_output(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/thakur/Android/Sdk/platform-tools/adb', '-P', '5037', '-s', 'emulator-5554', 'shell', 'date', '1015153423.00']' returned non-zero exit status 1.
E1208 08:41:04.576442 140126432224768 adb_controller.py:135] **stdout**:
E1208 08:41:04.576720 140126432224768 adb_controller.py:137]     b'date: cannot set date: Operation not permitted'
E1208 08:41:04.577079 140126432224768 adb_controller.py:137]     b'Sun Oct 15 15:34:00 UTC 2023'
E1208 08:41:11.400331 140126432224768 adb_controller.py:131] Failed to execute ADB command (try 2 of 3): [adb -P 5037 -s emulator-5554 shell date 1015153423.00]
Traceback (most recent call last):
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/components/adb_controller.py", line 122, in execute_command
    cmd_output = subprocess.check_output(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/thakur/Android/Sdk/platform-tools/adb', '-P', '5037', '-s', 'emulator-5554', 'shell', 'date', '1015153423.00']' returned non-zero exit status 1.
E1208 08:41:11.400967 140126432224768 adb_controller.py:135] **stdout**:
E1208 08:41:11.401081 140126432224768 adb_controller.py:137]     b'date: cannot set date: Operation not permitted'
E1208 08:41:11.401140 140126432224768 adb_controller.py:137]     b'Sun Oct 15 15:34:00 UTC 2023'
Traceback (most recent call last):
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/components/adb_controller.py", line 122, in execute_command
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/thakur/Android/Sdk/platform-tools/adb', '-P', '5037', '-s', 'emulator-5554', 'shell', 'date', '1015153423.00']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/anuthakur/Documents/android_world/android_world/minimal_task_runner.py", line 130, in <module>
    app.run(main)
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/mnt/c/Users/anuthakur/Documents/android_world/android_world/minimal_task_runner.py", line 126, in main
    _main()
  File "/mnt/c/Users/anuthakur/Documents/android_world/android_world/minimal_task_runner.py", line 106, in _main
    task.initialize_task(env)
  File "/mnt/c/Users/anuthakur/Documents/android_world/android_world/android_world/task_evals/composite/system.py", line 73, in initialize_task
    super().initialize_task(env)
  File "/mnt/c/Users/anuthakur/Documents/android_world/android_world/android_world/task_evals/task_eval.py", line 136, in initialize_task
    self.initialize_device_time(env)
  File "/mnt/c/Users/anuthakur/Documents/android_world/android_world/android_world/task_evals/task_eval.py", line 130, in initialize_device_time
    datetime_utils.set_datetime(env.controller, self.device_time)
  File "/mnt/c/Users/anuthakur/Documents/android_world/android_world/android_world/utils/datetime_utils.py", line 158, in set_datetime
    _set_datetime(env, dt)
  File "/mnt/c/Users/anuthakur/Documents/android_world/android_world/android_world/utils/datetime_utils.py", line 210, in _set_datetime
    adb_utils.issue_generic_request(
  File "/mnt/c/Users/anuthakur/Documents/android_world/android_world/android_world/env/adb_utils.py", line 528, in issue_generic_request
    response = env.execute_adb_call(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/wrappers/base_wrapper.py", line 101, in execute_adb_call
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/wrappers/base_wrapper.py", line 101, in execute_adb_call
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/environment.py", line 150, in execute_adb_call
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/components/coordinator.py", line 181, in execute_adb_call
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/components/adb_call_parser.py", line 111, in parse
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/components/adb_call_parser.py", line 757, in _handle_generic
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/components/adb_call_parser.py", line 81, in _execute_command
  File "/home/thakur/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/components/adb_controller.py", line 147, in execute_command
android_env.components.errors.AdbControllerError: Error executing adb command: [adb -P 5037 -s emulator-5554 shell date 1015153423.00]
Caused by: Command '['/home/thakur/Android/Sdk/platform-tools/adb', '-P', '5037', '-s', 'emulator-5554', 'shell', 'date', '1015153423.00']' returned non-zero exit status 1.
adb stdout: [b'date: cannot set date: Operation not permitted\nSun Oct 15 15:34:00 UTC 2023\n']
adb stderr: [None]
(android_world) thakur@INBAWN180334:/mnt/c/Users/anuthakur/Documents/android_world/android_world$

**Comment by crawles** [comment]
Can you try the solution in: https://github.com/google-research/android_world/issues/118#issuecomment-2458071923

**Comment by ThakurAnunaya** [comment]
Thanks, That worked. will it only work with gpt-4-turbo-2024-04-09? or I can use any other model?

**Comment by crawles** [comment]
I am glad. You can use any model.

Chris
